### ISSUE TITLE
Can't Login to ITSM-NG

### ISSUE THREAD

**Issue by tosinosu** [itsmng/itsmng-docker#18]
I have used the docker compose file provided to install itsm in a docker 

```
version: '3'
services:
  itsmweb:
    image: docker.io/itsmng/itsm-ng:2.0.0_rc3
    depends_on:
      - itsmdb
    container_name: itsmweb
    restart: always
    ports:
      - 8080:80
    volumes:
      - itsmng-config:/var/www/itsm-ng/config
      - itsmng-plugins:/var/www/itsm-ng/plugins
      - itsmng-files:/var/www/itsm-ng/files
    environment:
      MARIADB_HOST: itsmdb
      MARIADB_USER: itsmng
      MARIADB_PASSWORD: itsmng
      MARIADB_DATABASE: itsmng
  itsmdb:
    image: docker.io/mariadb:10.6
    container_name: itsmdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - itsmng-data:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: iamastrongpassword
      MARIADB_USER: itsmng
      MARIADB_PASSWORD: itsmng
      MARIADB_DATABASE: itsmng

volumes:
  itsmng-config:
  itsmng-plugins:
  itsmng-files:
  itsmng-data:

```

The page opened and everything looked fine until I entered the username (itsmng) and password (itsmng) which returned "Incorrect username or password: Log in again" error.

I have also tried "itsm" as the username and password without any luck. When I tried "itsm", the returned page was blank. Same applies to using "tech" as the username and password.

Could someone help check this or provide the correct default username and password if the ones entered above are incorrect?

**Comment by minzords** [comment]
Hello,

The username and password is `itsm`.

Best regards

**Comment by tosinosu** [comment]
I tried "itsm" as the username and password but it only shows a blank page afterwards.  I have used the list of browsers below to test this, all with the same result. If you wouldn't mind, you can also try it out on the browsers and revert with your observations

-  Microsoft Edge: Version 123.0.2420.65 (Official build) (64-bit)
- Firefox: 115.8.0esr (64-bit Kali Ditro
-  Chromium: Version 122.0.6261.57 (Official Build) built on Debian trixie/sid, running on Debian kali-rolling (64-bit)

**Comment by minzords** [comment]
Hello,

The fix is available, use the latest docker images

```
version: '3'
services:
  itsmweb:
    image: docker.io/minzords/itsmng:2.0.0_rc4
    depends_on:
      - itsmdb
    container_name: itsmweb
    restart: always
    ports:
      - 8080:80
    volumes:
      - itsmng-config:/var/www/itsm-ng/config
      - itsmng-plugins:/var/www/itsm-ng/plugins
      - itsmng-files:/var/www/itsm-ng/files
    environment:
      MARIADB_HOST: itsmdb
      MARIADB_USER: itsmng
      MARIADB_PASSWORD: itsmng
      MARIADB_DATABASE: itsmng
  itsmdb:
    image: docker.io/mariadb:10.6
    container_name: itsmdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - itsmng-data:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: iamastrongpassword
      MARIADB_USER: itsmng
      MARIADB_PASSWORD: itsmng
      MARIADB_DATABASE: itsmng

volumes:
  itsmng-config:
  itsmng-plugins:
  itsmng-files:
  itsmng-data:
```

Best regards
